/* Generated By:JavaCC: Do not edit this line. AssignmentConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AssignmentConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 1;
  /** RegularExpression Id. */
  int PLUS = 2;
  /** RegularExpression Id. */
  int MULTIPLY = 3;
  /** RegularExpression Id. */
  int DEF = 4;
  /** RegularExpression Id. */
  int END_OF_LINE = 5;
  /** RegularExpression Id. */
  int PARAM = 6;
  /** RegularExpression Id. */
  int FUNC_NAME = 7;
  /** RegularExpression Id. */
  int SEMICOLON = 8;
  /** RegularExpression Id. */
  int SPACE = 9;
  /** RegularExpression Id. */
  int OPEN_BRAC = 10;
  /** RegularExpression Id. */
  int CLOSE_BRAC = 11;
  /** RegularExpression Id. */
  int OPEN_PARENTHESIS = 12;
  /** RegularExpression Id. */
  int CLOSE_PARENTHESIS = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NUMBER>",
    "\"+\"",
    "\"*\"",
    "\"DEF\"",
    "<END_OF_LINE>",
    "<PARAM>",
    "<FUNC_NAME>",
    "\";\"",
    "\" \"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
  };

}
